### PR TITLE
Typescript 5.1.3 support + Dist

### PR DESCRIPTION
**Pull request by paikattilrohin**
Typescript Update to 5.1.3 requires a typedoc update to `0.24.8` which requires typedoc-plugin-version peer dependency version to be updated as well.

### CODE REVIEW

**Comment by whatisdot** [comment]
@paikattilrohin and I had a huddle where we discussed how we are going to handle making this update quickly while also enabling this to be merged into the parent project. We settled on the following:
1. Create a new branch named `dist/typescript-5.1.3-support` that contains the `typedoc` version update, along with all of the `dist/` files that are included in the build. This will enable us to test in our project(s).
1. Reset the `typescript-5.1.3-support` branch so it only contains commits that increase the version of `typedoc` (this PR).
1. After `typescript-5.1.3-support` is merged into the `main` branch of this fork, we create a `dist/main` branch that also includes the `dist/` files built from the `main` branch.
1. Set up branch protection rules to prevent individuals from pushing to `dist/main`.
1. Update the package.json in our project to use `github:snapsheet/typedoc-plugin-versions#dist/main`.
1. Use this package until we can submit a PR to [citkane/typedoc-plugin-versions](https://github.com/citkane/typedoc-plugin-versions) to include the `typedoc` version update.

This will enable us to continue our work without doing a full build and push of the project to our own NPM package repository, and all of the setup that would require.

**Review by whatisdot — APPROVED** [review]
I validated these changes through integration testing of a dependent project, and everything works as expected.

**Review by d10zero — APPROVED** [review]
Validated this change by updating Squire's `package.json` with this branch of `cdktf-infra`: `"github:bodyshopbidsdotcom/cdktf-infra#dist/dependabot/npm_and_yarn/typescript-5.1.3"`. I then ran the following
```
npx cdktf synth
npx cdktf diff squire-qa1
```

**Comment by whatisdot** [comment]
It looks like this [might never be fixed](https://github.com/citkane/typedoc-plugin-versions/issues/28#issuecomment-1660146404), unless Snapsheet picks up the project.

**Pull request merged**
